# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sharescore' do

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'MBProgressHUD'
pod 'SVProgressHUD'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sharescore`

  target 'SharescoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SharescoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
